#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/generic_account_identification1"

module RubyIso20022 module Messages module Pain001001


class AccountIdentification4Choice 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "AccountIdentification4Choice"

    
    has_one :othr, RubyIso20022::Messages::Pain001001::GenericAccountIdentification1, :tag => "Othr", :namespace => "ns1"
    
    element :iban, String, :tag => "IBAN", :namespace => "ns1"


  
end


end end end
