#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/postal_address24"

module RubyIso20022 module Messages module Pain001001


class BranchData3 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "BranchData3"

    
    element :id, String, :tag => "Id", :namespace => "ns1"
    
    element :lei, String, :tag => "LEI", :namespace => "ns1"
    
    element :nm, String, :tag => "Nm", :namespace => "ns1"
    
    has_one :pstl_adr, RubyIso20022::Messages::Pain001001::PostalAddress24, :tag => "PstlAdr", :namespace => "ns1"


  
end


end end end
