#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/cheque_delivery_method1_choice"
require "ruby_iso20022/messages/pain001001/name_and_address16"

module RubyIso20022 module Messages module Pain001001


class Cheque11 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "Cheque11"

    
    element :chq_tp, String, :tag => "ChqTp", :namespace => "ns1"
    
    element :chq_nb, String, :tag => "ChqNb", :namespace => "ns1"
    
    has_one :chq_fr, RubyIso20022::Messages::Pain001001::NameAndAddress16, :tag => "ChqFr", :namespace => "ns1"
    
    has_one :dlvry_mtd, RubyIso20022::Messages::Pain001001::ChequeDeliveryMethod1Choice, :tag => "DlvryMtd", :namespace => "ns1"
    
    has_one :dlvr_to, RubyIso20022::Messages::Pain001001::NameAndAddress16, :tag => "DlvrTo", :namespace => "ns1"
    
    element :instr_prty, String, :tag => "InstrPrty", :namespace => "ns1"
    
    element :chq_mtrty_dt, Date, :tag => "ChqMtrtyDt", :namespace => "ns1"
    
    element :frms_cd, String, :tag => "FrmsCd", :namespace => "ns1"
    
    has_many :memo_flds, String, :tag => "MemoFld", :namespace => "ns1"
    
    element :rgnl_clr_zone, String, :tag => "RgnlClrZone", :namespace => "ns1"
    
    element :prt_lctn, String, :tag => "PrtLctn", :namespace => "ns1"
    
    has_many :sgntrs, String, :tag => "Sgntr", :namespace => "ns1"


  
end


end end end
