#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/frequency36_choice"
require "ruby_iso20022/messages/pain001001/mandate_setup_reason1_choice"
require "ruby_iso20022/messages/pain001001/mandate_type_information2"

module RubyIso20022 module Messages module Pain001001


class CreditTransferMandateData1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "CreditTransferMandateData1"

    
    element :mndt_id, String, :tag => "MndtId", :namespace => "ns1"
    
    has_one :tp, RubyIso20022::Messages::Pain001001::MandateTypeInformation2, :tag => "Tp", :namespace => "ns1"
    
    element :dt_of_sgntr, Date, :tag => "DtOfSgntr", :namespace => "ns1"
    
    element :dt_of_vrfctn, DateTime, :tag => "DtOfVrfctn", :namespace => "ns1"
    
    element :elctrnc_sgntr, String, :tag => "ElctrncSgntr", :namespace => "ns1"
    
    element :frst_pmt_dt, Date, :tag => "FrstPmtDt", :namespace => "ns1"
    
    element :fnl_pmt_dt, Date, :tag => "FnlPmtDt", :namespace => "ns1"
    
    has_one :frqcy, RubyIso20022::Messages::Pain001001::Frequency36Choice, :tag => "Frqcy", :namespace => "ns1"
    
    has_one :rsn, RubyIso20022::Messages::Pain001001::MandateSetupReason1Choice, :tag => "Rsn", :namespace => "ns1"


  
end


end end end
