#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/creditor_reference_type2"

module RubyIso20022 module Messages module Pain001001


class CreditorReferenceInformation2 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "CreditorReferenceInformation2"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::CreditorReferenceType2, :tag => "Tp", :namespace => "ns1"
    
    element :ref, String, :tag => "Ref", :namespace => "ns1"


  
end


end end end
