#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"

module RubyIso20022 module Messages module Pain001001


class DatePeriod2 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DatePeriod2"

    
    element :fr_dt, Date, :tag => "FrDt", :namespace => "ns1"
    
    element :to_dt, Date, :tag => "ToDt", :namespace => "ns1"


  
end


end end end
