#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"

module RubyIso20022 module Messages module Pain001001


class DateAndDateTime2Choice 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DateAndDateTime2Choice"

    
    element :dt_tm, DateTime, :tag => "DtTm", :namespace => "ns1"
    
    element :dt, Date, :tag => "Dt", :namespace => "ns1"


  
end


end end end
