#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"
require "ruby_iso20022/messages/pain001001/discount_amount_type1_choice"

module RubyIso20022 module Messages module Pain001001


class DiscountAmountAndType1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DiscountAmountAndType1"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::DiscountAmountType1Choice, :tag => "Tp", :namespace => "ns1"
    
    has_one :amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "Amt", :namespace => "ns1"


  
end


end end end
