#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/document_line_identification1"
require "ruby_iso20022/messages/pain001001/remittance_amount3"

module RubyIso20022 module Messages module Pain001001


class DocumentLineInformation1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DocumentLineInformation1"

    
    has_many :ids, RubyIso20022::Messages::Pain001001::DocumentLineIdentification1, :tag => "Id", :namespace => "ns1"
    
    element :desc, String, :tag => "Desc", :namespace => "ns1"
    
    has_one :amt, RubyIso20022::Messages::Pain001001::RemittanceAmount3, :tag => "Amt", :namespace => "ns1"


  
end


end end end
