#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/document_line_type1"

module RubyIso20022 module Messages module Pain001001


class DocumentLineIdentification1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DocumentLineIdentification1"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::DocumentLineType1, :tag => "Tp", :namespace => "ns1"
    
    element :nb, String, :tag => "Nb", :namespace => "ns1"
    
    element :rltd_dt, Date, :tag => "RltdDt", :namespace => "ns1"


  
end


end end end
