#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"

module RubyIso20022 module Messages module Pain001001


class DocumentAdjustment1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "DocumentAdjustment1"

    
    has_one :amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "Amt", :namespace => "ns1"
    
    element :cdt_dbt_ind, String, :tag => "CdtDbtInd", :namespace => "ns1"
    
    element :rsn, String, :tag => "Rsn", :namespace => "ns1"
    
    element :addtl_inf, String, :tag => "AddtlInf", :namespace => "ns1"


  
end


end end end
