#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"

module RubyIso20022 module Messages module Pain001001


class EquivalentAmount2 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "EquivalentAmount2"

    
    has_one :amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "Amt", :namespace => "ns1"
    
    element :ccy_of_trf, String, :tag => "CcyOfTrf", :namespace => "ns1"


  
end


end end end
