#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"

module RubyIso20022 module Messages module Pain001001


class FrequencyAndMoment1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "FrequencyAndMoment1"

    
    element :tp, String, :tag => "Tp", :namespace => "ns1"
    
    element :pt_in_tm, String, :tag => "PtInTm", :namespace => "ns1"


  
end


end end end
