#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"
require "ruby_iso20022/messages/pain001001/garnishment_type1"
require "ruby_iso20022/messages/pain001001/party_identification135"

module RubyIso20022 module Messages module Pain001001


class Garnishment3 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "Garnishment3"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::GarnishmentType1, :tag => "Tp", :namespace => "ns1"
    
    has_one :grnshee, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "Grnshee", :namespace => "ns1"
    
    has_one :grnshmt_admstr, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "GrnshmtAdmstr", :namespace => "ns1"
    
    element :ref_nb, String, :tag => "RefNb", :namespace => "ns1"
    
    element :dt, Date, :tag => "Dt", :namespace => "ns1"
    
    has_one :rmtd_amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "RmtdAmt", :namespace => "ns1"
    
    element :fmly_mdcl_insrnc_ind, Boolean, :tag => "FmlyMdclInsrncInd", :namespace => "ns1"
    
    element :mplyee_termntn_ind, Boolean, :tag => "MplyeeTermntnInd", :namespace => "ns1"


  
end


end end end
