#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/financial_identification_scheme_name1_choice"

module RubyIso20022 module Messages module Pain001001


class GenericFinancialIdentification1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "GenericFinancialIdentification1"

    
    element :id, String, :tag => "Id", :namespace => "ns1"
    
    has_one :schme_nm, RubyIso20022::Messages::Pain001001::FinancialIdentificationSchemeName1Choice, :tag => "SchmeNm", :namespace => "ns1"
    
    element :issr, String, :tag => "Issr", :namespace => "ns1"


  
end


end end end
