#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/authorisation1_choice"
require "ruby_iso20022/messages/pain001001/branch_and_financial_institution_identification6"
require "ruby_iso20022/messages/pain001001/party_identification135"
require "ruby_iso20022/messages/pain001001/payment_initiation_source1"

module RubyIso20022 module Messages module Pain001001


class GroupHeader95 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "GroupHeader95"

    
    element :msg_id, String, :tag => "MsgId", :namespace => "ns1"
    
    element :cre_dt_tm, DateTime, :tag => "CreDtTm", :namespace => "ns1"
    
    has_many :authstns, RubyIso20022::Messages::Pain001001::Authorisation1Choice, :tag => "Authstn", :namespace => "ns1"
    
    element :nb_of_txs, String, :tag => "NbOfTxs", :namespace => "ns1"
    
    element :ctrl_sum, Float, :tag => "CtrlSum", :namespace => "ns1"
    
    has_one :initg_pty, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "InitgPty", :namespace => "ns1"
    
    has_one :fwdg_agt, RubyIso20022::Messages::Pain001001::BranchAndFinancialInstitutionIdentification6, :tag => "FwdgAgt", :namespace => "ns1"
    
    has_one :initn_src, RubyIso20022::Messages::Pain001001::PaymentInitiationSource1, :tag => "InitnSrc", :namespace => "ns1"


  
end


end end end
