#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/generic_organisation_identification1"

module RubyIso20022 module Messages module Pain001001


class OrganisationIdentification29 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "OrganisationIdentification29"

    
    element :any_bic, String, :tag => "AnyBIC", :namespace => "ns1"
    
    element :lei, String, :tag => "LEI", :namespace => "ns1"
    
    has_many :othrs, RubyIso20022::Messages::Pain001001::GenericOrganisationIdentification1, :tag => "Othr", :namespace => "ns1"


  
end


end end end
