#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/organisation_identification29"
require "ruby_iso20022/messages/pain001001/person_identification13"

module RubyIso20022 module Messages module Pain001001


class Party38Choice 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "Party38Choice"

    
    has_one :prvt_id, RubyIso20022::Messages::Pain001001::PersonIdentification13, :tag => "PrvtId", :namespace => "ns1"
    
    has_one :org_id, RubyIso20022::Messages::Pain001001::OrganisationIdentification29, :tag => "OrgId", :namespace => "ns1"


  
end


end end end
