#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"

module RubyIso20022 module Messages module Pain001001


class PaymentInitiationSource1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "PaymentInitiationSource1"

    
    element :nm, String, :tag => "Nm", :namespace => "ns1"
    
    element :prvdr, String, :tag => "Prvdr", :namespace => "ns1"
    
    element :vrsn, String, :tag => "Vrsn", :namespace => "ns1"


  
end


end end end
