#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/advice_type1"
require "ruby_iso20022/messages/pain001001/branch_and_financial_institution_identification6"
require "ruby_iso20022/messages/pain001001/cash_account38"
require "ruby_iso20022/messages/pain001001/credit_transfer_transaction40"
require "ruby_iso20022/messages/pain001001/date_and_date_time2_choice"
require "ruby_iso20022/messages/pain001001/party_identification135"
require "ruby_iso20022/messages/pain001001/payment_type_information26"

module RubyIso20022 module Messages module Pain001001


class PaymentInstruction34 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "PaymentInstruction34"

    
    element :pmt_inf_id, String, :tag => "PmtInfId", :namespace => "ns1"
    
    element :pmt_mtd, String, :tag => "PmtMtd", :namespace => "ns1"
    
    has_one :reqd_advc_tp, RubyIso20022::Messages::Pain001001::AdviceType1, :tag => "ReqdAdvcTp", :namespace => "ns1"
    
    element :btch_bookg, Boolean, :tag => "BtchBookg", :namespace => "ns1"
    
    element :nb_of_txs, String, :tag => "NbOfTxs", :namespace => "ns1"
    
    element :ctrl_sum, Float, :tag => "CtrlSum", :namespace => "ns1"
    
    has_one :pmt_tp_inf, RubyIso20022::Messages::Pain001001::PaymentTypeInformation26, :tag => "PmtTpInf", :namespace => "ns1"
    
    has_one :reqd_exctn_dt, RubyIso20022::Messages::Pain001001::DateAndDateTime2Choice, :tag => "ReqdExctnDt", :namespace => "ns1"
    
    element :poolg_adjstmnt_dt, Date, :tag => "PoolgAdjstmntDt", :namespace => "ns1"
    
    has_one :dbtr, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "Dbtr", :namespace => "ns1"
    
    has_one :dbtr_acct, RubyIso20022::Messages::Pain001001::CashAccount38, :tag => "DbtrAcct", :namespace => "ns1"
    
    has_one :dbtr_agt, RubyIso20022::Messages::Pain001001::BranchAndFinancialInstitutionIdentification6, :tag => "DbtrAgt", :namespace => "ns1"
    
    has_one :dbtr_agt_acct, RubyIso20022::Messages::Pain001001::CashAccount38, :tag => "DbtrAgtAcct", :namespace => "ns1"
    
    element :instr_for_dbtr_agt, String, :tag => "InstrForDbtrAgt", :namespace => "ns1"
    
    has_one :ultmt_dbtr, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "UltmtDbtr", :namespace => "ns1"
    
    element :chrg_br, String, :tag => "ChrgBr", :namespace => "ns1"
    
    has_one :chrgs_acct, RubyIso20022::Messages::Pain001001::CashAccount38, :tag => "ChrgsAcct", :namespace => "ns1"
    
    has_one :chrgs_acct_agt, RubyIso20022::Messages::Pain001001::BranchAndFinancialInstitutionIdentification6, :tag => "ChrgsAcctAgt", :namespace => "ns1"
    
    has_many :cdt_trf_tx_inves, RubyIso20022::Messages::Pain001001::CreditTransferTransaction40, :tag => "CdtTrfTxInf", :namespace => "ns1"


  
end


end end end
