#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/category_purpose1_choice"
require "ruby_iso20022/messages/pain001001/local_instrument2_choice"
require "ruby_iso20022/messages/pain001001/service_level8_choice"

module RubyIso20022 module Messages module Pain001001


class PaymentTypeInformation26 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "PaymentTypeInformation26"

    
    element :instr_prty, String, :tag => "InstrPrty", :namespace => "ns1"
    
    has_many :svc_lvls, RubyIso20022::Messages::Pain001001::ServiceLevel8Choice, :tag => "SvcLvl", :namespace => "ns1"
    
    has_one :lcl_instrm, RubyIso20022::Messages::Pain001001::LocalInstrument2Choice, :tag => "LclInstrm", :namespace => "ns1"
    
    has_one :ctgy_purp, RubyIso20022::Messages::Pain001001::CategoryPurpose1Choice, :tag => "CtgyPurp", :namespace => "ns1"


  
end


end end end
