#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/date_and_place_of_birth1"
require "ruby_iso20022/messages/pain001001/generic_person_identification1"

module RubyIso20022 module Messages module Pain001001


class PersonIdentification13 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "PersonIdentification13"

    
    has_one :dt_and_plc_of_birth, RubyIso20022::Messages::Pain001001::DateAndPlaceOfBirth1, :tag => "DtAndPlcOfBirth", :namespace => "ns1"
    
    has_many :othrs, RubyIso20022::Messages::Pain001001::GenericPersonIdentification1, :tag => "Othr", :namespace => "ns1"


  
end


end end end
