#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/address_type3_choice"

module RubyIso20022 module Messages module Pain001001


class PostalAddress24 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "PostalAddress24"

    
    has_one :adr_tp, RubyIso20022::Messages::Pain001001::AddressType3Choice, :tag => "AdrTp", :namespace => "ns1"
    
    element :dept, String, :tag => "Dept", :namespace => "ns1"
    
    element :sub_dept, String, :tag => "SubDept", :namespace => "ns1"
    
    element :strt_nm, String, :tag => "StrtNm", :namespace => "ns1"
    
    element :bldg_nb, String, :tag => "BldgNb", :namespace => "ns1"
    
    element :bldg_nm, String, :tag => "BldgNm", :namespace => "ns1"
    
    element :flr, String, :tag => "Flr", :namespace => "ns1"
    
    element :pst_bx, String, :tag => "PstBx", :namespace => "ns1"
    
    element :room, String, :tag => "Room", :namespace => "ns1"
    
    element :pst_cd, String, :tag => "PstCd", :namespace => "ns1"
    
    element :twn_nm, String, :tag => "TwnNm", :namespace => "ns1"
    
    element :twn_lctn_nm, String, :tag => "TwnLctnNm", :namespace => "ns1"
    
    element :dstrct_nm, String, :tag => "DstrctNm", :namespace => "ns1"
    
    element :ctry_sub_dvsn, String, :tag => "CtrySubDvsn", :namespace => "ns1"
    
    element :ctry, String, :tag => "Ctry", :namespace => "ns1"
    
    has_many :adr_lines, String, :tag => "AdrLine", :namespace => "ns1"


  
end


end end end
