#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/proxy_account_type1_choice"

module RubyIso20022 module Messages module Pain001001


class ProxyAccountIdentification1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "ProxyAccountIdentification1"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::ProxyAccountType1Choice, :tag => "Tp", :namespace => "ns1"
    
    element :id, String, :tag => "Id", :namespace => "ns1"


  
end


end end end
