#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/referred_document_type3_choice"

module RubyIso20022 module Messages module Pain001001


class ReferredDocumentType4 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "ReferredDocumentType4"

    
    has_one :cd_or_prtry, RubyIso20022::Messages::Pain001001::ReferredDocumentType3Choice, :tag => "CdOrPrtry", :namespace => "ns1"
    
    element :issr, String, :tag => "Issr", :namespace => "ns1"


  
end


end end end
