#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/document_line_information1"
require "ruby_iso20022/messages/pain001001/referred_document_type4"

module RubyIso20022 module Messages module Pain001001


class ReferredDocumentInformation7 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "ReferredDocumentInformation7"

    
    has_one :tp, RubyIso20022::Messages::Pain001001::ReferredDocumentType4, :tag => "Tp", :namespace => "ns1"
    
    element :nb, String, :tag => "Nb", :namespace => "ns1"
    
    element :rltd_dt, Date, :tag => "RltdDt", :namespace => "ns1"
    
    has_many :line_dtls, RubyIso20022::Messages::Pain001001::DocumentLineInformation1, :tag => "LineDtls", :namespace => "ns1"


  
end


end end end
