#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/regulatory_authority2"
require "ruby_iso20022/messages/pain001001/structured_regulatory_reporting3"

module RubyIso20022 module Messages module Pain001001


class RegulatoryReporting3 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "RegulatoryReporting3"

    
    element :dbt_cdt_rptg_ind, String, :tag => "DbtCdtRptgInd", :namespace => "ns1"
    
    has_one :authrty, RubyIso20022::Messages::Pain001001::RegulatoryAuthority2, :tag => "Authrty", :namespace => "ns1"
    
    has_many :dtls, RubyIso20022::Messages::Pain001001::StructuredRegulatoryReporting3, :tag => "Dtls", :namespace => "ns1"


  
end


end end end
