#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/name_and_address16"

module RubyIso20022 module Messages module Pain001001


class RemittanceLocationData1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "RemittanceLocationData1"

    
    element :mtd, String, :tag => "Mtd", :namespace => "ns1"
    
    element :elctrnc_adr, String, :tag => "ElctrncAdr", :namespace => "ns1"
    
    has_one :pstl_adr, RubyIso20022::Messages::Pain001001::NameAndAddress16, :tag => "PstlAdr", :namespace => "ns1"


  
end


end end end
