#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/remittance_location_data1"

module RubyIso20022 module Messages module Pain001001


class RemittanceLocation7 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "RemittanceLocation7"

    
    element :rmt_id, String, :tag => "RmtId", :namespace => "ns1"
    
    has_many :rmt_lctn_dtls, RubyIso20022::Messages::Pain001001::RemittanceLocationData1, :tag => "RmtLctnDtls", :namespace => "ns1"


  
end


end end end
