#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/structured_remittance_information16"

module RubyIso20022 module Messages module Pain001001


class RemittanceInformation16 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "RemittanceInformation16"

    
    has_many :ustrds, String, :tag => "Ustrd", :namespace => "ns1"
    
    has_many :strds, RubyIso20022::Messages::Pain001001::StructuredRemittanceInformation16, :tag => "Strd", :namespace => "ns1"


  
end


end end end
