#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/creditor_reference_information2"
require "ruby_iso20022/messages/pain001001/garnishment3"
require "ruby_iso20022/messages/pain001001/party_identification135"
require "ruby_iso20022/messages/pain001001/referred_document_information7"
require "ruby_iso20022/messages/pain001001/remittance_amount2"
require "ruby_iso20022/messages/pain001001/tax_information7"

module RubyIso20022 module Messages module Pain001001


class StructuredRemittanceInformation16 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "StructuredRemittanceInformation16"

    
    has_many :rfrd_doc_inves, RubyIso20022::Messages::Pain001001::ReferredDocumentInformation7, :tag => "RfrdDocInf", :namespace => "ns1"
    
    has_one :rfrd_doc_amt, RubyIso20022::Messages::Pain001001::RemittanceAmount2, :tag => "RfrdDocAmt", :namespace => "ns1"
    
    has_one :cdtr_ref_inf, RubyIso20022::Messages::Pain001001::CreditorReferenceInformation2, :tag => "CdtrRefInf", :namespace => "ns1"
    
    has_one :invcr, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "Invcr", :namespace => "ns1"
    
    has_one :invcee, RubyIso20022::Messages::Pain001001::PartyIdentification135, :tag => "Invcee", :namespace => "ns1"
    
    has_one :tax_rmt, RubyIso20022::Messages::Pain001001::TaxInformation7, :tag => "TaxRmt", :namespace => "ns1"
    
    has_one :grnshmt_rmt, RubyIso20022::Messages::Pain001001::Garnishment3, :tag => "GrnshmtRmt", :namespace => "ns1"
    
    has_many :addtl_rmt_inves, String, :tag => "AddtlRmtInf", :namespace => "ns1"


  
end


end end end
