#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/supplementary_data_envelope1"

module RubyIso20022 module Messages module Pain001001


class SupplementaryData1 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "SupplementaryData1"

    
    element :plc_and_nm, String, :tag => "PlcAndNm", :namespace => "ns1"
    
    has_one :envlp, RubyIso20022::Messages::Pain001001::SupplementaryDataEnvelope1, :tag => "Envlp", :namespace => "ns1"


  
end


end end end
