#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"
require "ruby_iso20022/messages/pain001001/tax_record_details2"

module RubyIso20022 module Messages module Pain001001


class TaxAmount2 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "TaxAmount2"

    
    element :rate, Float, :tag => "Rate", :namespace => "ns1"
    
    has_one :taxbl_base_amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "TaxblBaseAmt", :namespace => "ns1"
    
    has_one :ttl_amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "TtlAmt", :namespace => "ns1"
    
    has_many :dtls, RubyIso20022::Messages::Pain001001::TaxRecordDetails2, :tag => "Dtls", :namespace => "ns1"


  
end


end end end
