#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/active_or_historic_currency_and_amount"
require "ruby_iso20022/messages/pain001001/tax_party1"
require "ruby_iso20022/messages/pain001001/tax_party2"
require "ruby_iso20022/messages/pain001001/tax_record2"

module RubyIso20022 module Messages module Pain001001


class TaxInformation7 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "TaxInformation7"

    
    has_one :cdtr, RubyIso20022::Messages::Pain001001::TaxParty1, :tag => "Cdtr", :namespace => "ns1"
    
    has_one :dbtr, RubyIso20022::Messages::Pain001001::TaxParty2, :tag => "Dbtr", :namespace => "ns1"
    
    has_one :ultmt_dbtr, RubyIso20022::Messages::Pain001001::TaxParty2, :tag => "UltmtDbtr", :namespace => "ns1"
    
    element :admstn_zone, String, :tag => "AdmstnZone", :namespace => "ns1"
    
    element :ref_nb, String, :tag => "RefNb", :namespace => "ns1"
    
    element :mtd, String, :tag => "Mtd", :namespace => "ns1"
    
    has_one :ttl_taxbl_base_amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "TtlTaxblBaseAmt", :namespace => "ns1"
    
    has_one :ttl_tax_amt, RubyIso20022::Messages::Pain001001::ActiveOrHistoricCurrencyAndAmount, :tag => "TtlTaxAmt", :namespace => "ns1"
    
    element :dt, Date, :tag => "Dt", :namespace => "ns1"
    
    element :seq_nb, Float, :tag => "SeqNb", :namespace => "ns1"
    
    has_many :rcrds, RubyIso20022::Messages::Pain001001::TaxRecord2, :tag => "Rcrd", :namespace => "ns1"


  
end


end end end
