#
# Auto-generated by jaxb2ruby https://github.com/sshaw/jaxb2ruby
#

require "happymapper"
require "ruby_iso20022/messages/pain001001/tax_authorisation1"

module RubyIso20022 module Messages module Pain001001


class TaxParty2 
  include HappyMapper

    register_namespace "ns1", "urn:iso:std:iso:20022:tech:xsd:pain.001.001.10"


  tag "TaxParty2"

    
    element :tax_id, String, :tag => "TaxId", :namespace => "ns1"
    
    element :regn_id, String, :tag => "RegnId", :namespace => "ns1"
    
    element :tax_tp, String, :tag => "TaxTp", :namespace => "ns1"
    
    has_one :authstn, RubyIso20022::Messages::Pain001001::TaxAuthorisation1, :tag => "Authstn", :namespace => "ns1"


  
end


end end end
